version: '3'
services:
  db:
    image: mysql:5.6
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123

  app:
    links:
     - db
    build: .
    image: nazmulb/api_integration_test
    volumes:
      - .:/var/www/html
    ports:
      - "8082:8082"
    environment:
      DEV_DATABASE_URL: "mysql://root:123@db:3306/apimicro_dev"
      TEST_DATABASE_URL: "mysql://root:123@db:3306/apimicro_test"
